config:
  credentials: []
  project_repos:
    git.man.poznan.pl/stash/scm/eosc-rs/online-ml-ai-engine:
      branch: master
      repo: https://git.man.poznan.pl/stash/scm/eosc-rs/online-ml-ai-engine.git
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.8
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/online-ml-ai-engine git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-maroon-echidna.sh
        container: qc.acc_crappy-pumpkin-cat
  QC.Doc:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/online-ml-ai-engine find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-orange-lemming.sh
        container: qc.doc_thirsty-sangria-dachsbracke
      git.man.poznan.pl/stash/scm/eosc-rs/online-ml-ai-engine git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-harlequin-fox.sh
        container: qc.doc_wiggy-puce-hamster
      git.man.poznan.pl/stash/scm/eosc-rs/online-ml-ai-engine markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-fuchsia-caiman.sh
        container: qc.doc_shaky-ecru-uakari
  QC.Lic:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/online-ml-ai-engine licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-periwinkle-leopard.sh
        container: qc.lic_pretty-cardinal-grouse
  QC.Met:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/online-ml-ai-engine cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-wheat-heron.sh
        container: qc.met_homely-amethyst-hyrax
  QC.Sec:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/online-ml-ai-engine bandit:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-linen-donkey.sh
        container: qc.sec_gamy-magenta-cockroach
  QC.Sty:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/online-ml-ai-engine flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-beige-antelope.sh
        container: qc.sty_hilly-wheat-dingo
      git.man.poznan.pl/stash/scm/eosc-rs/online-ml-ai-engine hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-linen-barb.sh
        container: qc.sty_squeaky-saffron-dane
      git.man.poznan.pl/stash/scm/eosc-rs/online-ml-ai-engine jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-ochre-bulldog.sh
        container: qc.sty_thirsty-orchid-booby
  QC.Ver:
    repos:
      git.man.poznan.pl/stash/scm/eosc-rs/online-ml-ai-engine get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-copper-budgerigar.sh
        container: qc.ver_snappy-bistre-spaniel
timeout: 5400
